### ISSUE TITLE
App does not show any results

### ISSUE THREAD

**Issue by btadine** [amadeus4dev/amadeus-hotel-search-swift#1]
### Environment: 
-Simulator. 
-iPod Touch. 
-iOS 15.2
-Test API

### How to reproduce:
-Open the app and tap on the search button. On the console, A log indicating 0 results appears.

### Hypothetical cause:
-After trying manually to fetch the same endpoints, looks like, for some reason, v2 API endpoint `hotel-offers` throws `invalid access token` error. After debugging the app looks like it has this issue as well too.

-V3 API endpoint requires Amadeus listing ids as a parameter so it breaks the whole idea of searching in a city randomly.

**Comment by tsolakoua** [comment]
Hello, could you please get in touch with the support at https://developers.amadeus.com/ for that issue? Newly created accounts don't have access to the Hotel Search v2 API by default and the technical team will need to know your account in order to grant you access to the API.

**Comment by btadine** [comment]
Hey @tsolakoua thanks! I will do that. I didn't found this on the documentation so I was clueless.
